apiVersion: apps/v1beta1
kind: Deployment
metadata:
        name: "posgres-controller"
spec:
        replicas: 1
        template:
                metadata:
                        labels:
                                app: posgres-controller
                spec:
                        serviceAccountName: default
                        containers:
                                - name: posgres-controller
                                  image: wlan0/posgres-controller:v0.0.1
                                  imagePullPolicy: Always
                                  args:
                                          - --in-cluster
                                  env:
                                          - name: SELF_IP
                                            valueFrom:
                                                    fieldRef:
                                                            fieldPath: status.podIP

---

apiVersion: v1
kind: Service
metadata: 
        name: posgres-controller
        namespace: default
        labels:
                app: posgres-controller
spec:
        selector:
                app: posgres-controller
        type: LoadBalancer 
        ports:
                - port: 8081
                  name: web
                - port: 8080
                  name: api

